### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by guillaumebdx** [afeynaud/vcab33#4]
Add this viewport : `<meta name="viewport" content="width=device-width, initial-scale=1">`

https://github.com/afeynaud/vcab33/blob/58c33d6cb034fc2e35bc8a6b5c0418e12a8976c8/index.html#L6

**Comment by afeynaud** [comment]
Hello Guillaume. Meta viewport was successful added to do responsive design. Thanks for your contribution.
